# Generated by Django 5.0.6 on 2024-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RecipeApplication", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="user",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="recipe",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.SmallIntegerField(),
        ),
    ]
