# Generated by Django 4.1.7 on 2024-05-22 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "RecipeApplication",
            "0002_alter_review_unique_together_alter_recipe_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="user",
        ),
    ]
